---
- name: Configure NAT on R2
  hosts: R2
  gather_facts: false
  connection: local

  tasks:
    - name: Configure NAT on R2
      ios_config:
        lines:
          - ip nat inside source static 192.168.254.2 10.0.0.4

    - name: Configure NAT inside interface
      ios_config:
        lines:
          - ip nat inside
        parents: interface FastEthernet0/0
    
    - name: Configure NAT outside interface
      ios_config:
        lines:
          - ip nat outside
        parents: interface Serial0/0
