---
# Initial configuration testing
- import_playbook: tasks/test_ansible-node_connectivity.yaml
- import_playbook: tasks/backup_startup-config.yaml
- import_playbook: tasks/get_ipv4.yaml

# Network Topic 1 - Dynamic Routing (EIGRP)
- import_playbook: tasks/eigrp-config.yaml
# Network Topic 2 - Network Address Translation (NAT)
- import_playbook: tasks/nat-config.yaml
# Network Topic 3 - Access Lists (ACLs)
- import_playbook: tasks/acl-config.yaml

# Saving configuration
- import_playbook: tasks/backup_running-config.yaml
# - import_playbook: tasks/save_config.yaml

# Additional: Deployment of a static web page
- import_playbook: tasks/deploy-static-html.yaml
